---
grails:
    profile: web-plugin
    codegen:
        defaultPackage: quercus.php
    doc:
        authors: Oscar Konno Sampaio, Hans Bogaards
spring:
    groovy:
        template:
            check-template-location: false
